#cloud-config
autoinstall:
  version: 1
  
  locale: es_ES.UTF-8
  keyboard:
    layout: es
  timezone: Europe/Madrid

network:
  version: 2
  ethernets:
    enp1s0:
      dhcp4: true

identity:
  username: admin
  hostname: usuario
  password: 'usuario'
